// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceHunt.Infrastructure.Persistence;

#nullable disable

namespace PriceHunt.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PriceHuntDbContext))]
    [Migration("20260930134752_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PriceHunt.Infrastructure.Persistence.SearchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ShipDateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ShipDateTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationNormalized");

                    b.HasIndex("OriginNormalized");

                    b.HasIndex("Status");

                    b.ToTable("Searches", (string)null);
                });

            modelBuilder.Entity("PriceHunt.Infrastructure.Persistence.SearchSupplierEntity", b =>
                {
                    b.Property<Guid>("SearchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("SearchId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SearchSuppliers", (string)null);
                });

            modelBuilder.Entity("PriceHunt.Infrastructure.Persistence.SupplierEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("PriceHunt.Infrastructure.Persistence.SupplierResponseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PriceMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SearchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PriceMinorUnits");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("ResponseTimeMs");

                    b.HasIndex("Outcome", "ReceivedAt");

                    b.HasIndex("SearchId", "SupplierId")
                        .IsUnique();

                    b.HasIndex("SupplierId", "ReceivedAt");

                    b.ToTable("SupplierResponses", (string)null);
                });

            modelBuilder.Entity("PriceHunt.Infrastructure.Persistence.SearchSupplierEntity", b =>
                {
                    b.HasOne("PriceHunt.Infrastructure.Persistence.SearchEntity", null)
                        .WithMany("Suppliers")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceHunt.Infrastructure.Persistence.SupplierEntity", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PriceHunt.Infrastructure.Persistence.SupplierResponseEntity", b =>
                {
                    b.HasOne("PriceHunt.Infrastructure.Persistence.SearchEntity", "Search")
                        .WithMany("Responses")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceHunt.Infrastructure.Persistence.SupplierEntity", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Search");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PriceHunt.Infrastructure.Persistence.SearchEntity", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
