// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceHunt.Api.Data;

#nullable disable

namespace PriceHunt.Api.Migrations
{
    [DbContext(typeof(PriceHuntDbContext))]
    partial class PriceHuntDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PriceHunt.Api.Data.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Supplier A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Supplier B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Supplier C"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Supplier D"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Supplier E"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Supplier F"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Supplier G"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
